### ISSUE TITLE
Error in README npm install instructions.

### ISSUE THREAD

**Issue by elchocarrero** [ijsto/strapi-plugin-migrate#18]
The readme instructions for installing the plugin with npm are missing the "npm run build" instruction.  The admin UI is not being rebuilt, hence the plugin is not appearing in the admin panel.

It could be:
`npm cache clean --force && npm run build && npm run develop`
instead of
`npm cache clean --force && npm run develop`

**Comment by ScottAgirs** [comment]
Hi @braulio-balanza thank you for pointing this out, would you be interested in submitting a PR for this?

**Comment by ScottAgirs** [comment]
Updated w 8238148c638d830342264506930b4c20dbfdeb57. Thank you @braulio-balanza

**Comment by elchocarrero** [comment]
> Updated w 8238148c638d830342264506930b4c20dbfdeb57. Thank you @braulio-balanza 

Sorry for the late reply, been hella busy. Glad you updated it!
